### PR TITLE
add error messages

### LINKED ISSUE #105: feathers-action-react better error message for absent selector
should validate `options` passed to `feathers-action-react` function here: https://github.com/ahdinosaur/feathers-action-react/blob/3e0baeafd0e4deb6f1de11802970aef2053aa373/index.js#L39

so we can replace this unhelpful error with a better error

``` error      TypeError: selector is not a function
    at Function.mapStateToProps [as mapToProps] (index.js:37)
    at mapToPropsProxy (wrapMapToProps.js:54)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:63)
    at mapToPropsProxy (wrapMapToProps.js:54)
    at handleFirstCall (selectorFactory.js:37)
    at pureFinalPropsSelector (selectorFactory.js:85)
    at Object.runComponentSelector [as run] (connectAdvanced.js:43)
    at Connect.initSelector (connectAdvanced.js:195)
    at new Connect (connectAdvanced.js:136)
    at ReactCompositeComponent.js:294```

### PR DESCRIPTION
**Pull request by sarah-arrrgh**
closes https://github.com/root-systems/cobuy/issues/105

- add assertions to check options is well structured
- add default values when options is undefined

### CODE REVIEW

**Review by iainkirkpatrick — APPROVED** [review]
nice, looks cool :)

**Comment by ahdinosaur** [comment]
@sarah-arrrgh  @iainkirkpatrick do you want to release a new minor version?

**Comment by sarah-arrrgh** [comment]
@ahdinosaur I don't know how to do that... @iainkirkpatrick ??

**Comment by ahdinosaur** [comment]
@sarah-arrrgh do you want to learn how to release a new module version?

basically just

```
npm version {major,minor,patch}
npm publish
git push origin master --tags
```

in this case, it's a _minor_ version.

**Pull request merged**
